
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.110:33306/mall?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
  redis:
    cluster:
      max-redirects: 3
      nodes:
        - 192.168.0.110:7000
        - 192.168.0.110:7001
        - 192.168.0.110:7002
        - 192.168.0.110:7003
        - 192.168.0.110:7004
        - 192.168.0.110:7005
    lettuce:
      pool:
        max-active: 1000
        max-idle: 10 # 连接池中最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）

  rabbitmq:
    addresses: 192.168.0.110
    port: 5672
    username: guest
    password: guest
  activemq:
    broker-url: tcp://192.168.0.110:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: false
myqueue: springboot-mall-queue

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # \u63A7\u5236\u53F0\u65E5\u5FD7\u914D\u7F6E
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
server:
  servlet:
    session:
      timeout: 120
